include:
  - project: 'team113sanger/common/cicd-template'
    ref: 0.3.3 # Use the latest Git Tag or if experimenting with new components use a Git SHA
    file: '.gitlab-ci-components.yml'

stages:
  - test


#############
# TEMPLATES #
#############

.generic-variables:
  extends:
    - .component-variables
  variables:
    USE_DOCKER_TARGET_STAGE: 1
    DOCKER_BUILDKIT: 1
    DOCKER_TARGET_STAGE: test
    TEST_FILE: run_tests.sh
    DOCKERFILE_PATH: "" # Must be set in the job definition
    DOCKER_BUILD_CONTEXT: .

.generic-script:
  script:
    - echo "Running a build and then test for the image"
    # 
    - echo "DOCKERFILE_PATH=${DOCKERFILE_PATH}"
    - echo "DOCKER_TARGET_STAGE=${DOCKER_TARGET_STAGE}"
    - echo "CANDIDATE_IMAGE=${CANDIDATE_IMAGE}"
    - echo "DOCKER_BUILD_CONTEXT=${DOCKER_BUILD_CONTEXT}"
    - echo "TEST_FILE=${TEST_FILE}"
    #
    - test -f ${DOCKERFILE_PATH:?}
    #
    # Build the image
    #
    - BUILD_CMD="docker build --target ${DOCKER_TARGET_STAGE:?} -t ${CANDIDATE_IMAGE:?} -f ${DOCKERFILE_PATH} --progress=plain ${DOCKER_BUILD_CONTEXT:?}"
    - echo "Running build command ${BUILD_CMD}"
    - eval ${BUILD_CMD}
    #
    # Test the image
    #
    - docker run --rm ${CANDIDATE_IMAGE:?} ls -l ${TEST_FILE:?}
    - docker run --rm ${CANDIDATE_IMAGE:?} bash ${TEST_FILE:?}
    - echo "Build and test completed successfully"


############
#   JOBS   #
############

test-ubuntu22-usr_local:
  stage: test
  variables:
    PRE_FETCH_BASE_IMAGE: ubuntu:22.04
    IMAGE_TAG_SUFFIX: ubuntu22+usr_local
    DOCKERFILE_PATH: Dockerfile.ubuntu22.usr_local
  extends:
      - .generic-variables
      - .component-before_script
      - .component-after_script
      - .component-tags-shared-runner

test-ubuntu22-custom:
  stage: test
  variables:
    PRE_FETCH_BASE_IMAGE: ubuntu:22.04
    IMAGE_TAG_SUFFIX: ubuntu22+custom
    DOCKERFILE_PATH: Dockerfile.ubuntu22.custom
  extends:
      - .generic-variables
      - .component-before_script
      - .component-after_script
      - .component-tags-shared-runner
